/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_FearlessUnicode */

#ifndef _Included_utils_FearlessUnicode
#define _Included_utils_FearlessUnicode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_FearlessUnicode
 * Method:    parse
 * Signature: (Ljava/lang/String;)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_utils_FearlessUnicode_parse
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
